### PR TITLE
Zero checksum handling for UDP4->UDP6

### PR DESCRIPTION
**Pull request by angus19**
MAP should be transparent to the UDP csum zero in both directions.

### CODE REVIEW

**Comment by ayourtch** [comment]
Was a zero UDP checksum standardized in IPv6 for all applications ? If yes - would you happen to have some references?

The closest I can find it https://www.rfc-editor.org/rfc/rfc6936, and it’s merely a discussion;
And I think even standandardization was mainly in the context of tunneled packets - so the zero checksum in IPv4 and IPv6 are not equivalent, I think.

That was my motivation in not handling it with equivalence - but if you could confirm that in practice that was a wrong idea, I am happy to merge this change.

**Comment by angus19** [comment]
My change comes out because of referring to the [CERNET MAP implementation](https://github.com/cernet/MAP). And in it UDP csum zero is retained. Thanks.

**Comment by ayourtch** [comment]
Ok, fair enough, thanks for the info. I guess should be no harm merging - if someone complains we can revisit this later.

**Comment by r-pats** [comment]
I'm all for this as we're seeing real world user impact without it, and we have it in the UDP6->UDP4 direction already (with the config flag set).

[RFC 8200](https://www.rfc-editor.org/rfc/rfc8200#page-28) does codify an exception for UDP-based tunnelling protocols.  Maybe if we squint enough we can pretend it's applicable here?

> As an exception to the default behavior, protocols that use UDP
>          as a tunnel encapsulation may enable zero-checksum mode for a
>          specific port (or set of ports) for sending and/or receiving.
>          Any node implementing zero-checksum mode must follow the
>          requirements specified in "Applicability Statement for the Use
>          of IPv6 UDP Datagrams with Zero Checksums" [[RFC6936](https://www.rfc-editor.org/rfc/rfc6936)].

**Comment by ayourtch** [comment]
Cool, if we see a real world impact *without* the change, makes sense to have merged it. Thanks a lot @angus19 !

**Comment by ayourtch** [comment]
Well setting zero_csum_pass to 1 is not much of a fix, is it - it rather masks the problem in the code. Also it is a change of defaults, which i would be a bit hesitant to do… 

Here’s an idea, what if we rewrite that bit as follows:

if (!udp->check) {
  if (zero_csum_pass) {
    // do nothing 
    break;
  }
  // recalculate the IPv6 checksum before adjusting 
  ip6_update_csum(…)
}
 // here we will have nonzero checksum, unmagic + remagic

so, if it’s UDP and the checksum is zero and we don’t pass the zero checksum, recalculate it ?

It will still be broken if we don’t have full payload since we can’t do the full calculation in this case, but should take care of other cases ?

what do you think ?

**Comment by angus19** [comment]
LGTM.
> It will still be broken if we don’t have full payload since we can’t do the full calculation in this case, but should take care of other cases ?
We may reassemble fragmented UDPs to have a full payload first before recalculating the checksum.
This should start with the UDP fragment and its L4 checksum is 0 when zero_csum_pass=0 is configured.

**Comment by ayourtch** [comment]
Cool. Let’s do step by step.  Reassembly is a much larger thing and a much smaller hopefully corner case, i am not fully sure on the benefit vs complexity and fragility it brings. 

I am away from computer now, only with phone - will either push the patch with this change in a few days, or you can push it and I merge it.

**Comment by angus19** [comment]
> Reassembly is a much larger thing and a much smaller hopefully corner case, i am not fully sure on the benefit vs complexity and fragility it brings.

I do not expect every incoming UDP fragment goes into reassembling process under zero_csum_pass=0.
What we care about are those fragments belonging to the checksum zero but, this is not easy to handle even if we already have a **try_reassembly** method.
Perhaps should put the reassembly aside... ?

**Comment by angus19** [comment]
Hmm, we seem to have the same issue at L1006-L1015 (nat46-core.c).
`if ((udp->check == 0) && zero_csum_pass) {`
`  /* zero checksum and the config to pass it is set - do nothing with it */`
`  break;`
`}`
`sum1 = csum_ipv6_unmagic(nat46, &ip6h->saddr, &ip6h->daddr, infrag_payload_len, NEXTHDR_UDP, udp->check);`
`sum2 = csum_tcpudp_remagic(v4saddr, v4daddr, infrag_payload_len, NEXTHDR_UDP, sum1); /* add pseudoheader */`
`if(ul_sum) {`
`  *ul_sum = csum16_upd(*ul_sum, udp->check, sum2);`
`  }`
`udp->check = sum2;`

**Pull request merged**
