### PR TITLE
get rid of VLA on the stack, and fix the resulting error of a too lar…

### PR DESCRIPTION
**Pull request by ayourtch**
…ge stack frame

Previously the config parsing buffers were allocated to be 1K, this makes
the stack frame more than 2K. Reduce the buffers down to 200 bytes.

### CODE REVIEW

**Comment by ayourtch** [comment]
In testing the "poor man's CI" I noticed there was a VLA-related warning, and seems like using 2K of stack space is frowned upon :-) (somewhat unsurprisingly). Given that it's apparently not been a problem for years and may have implications, I am going to let this sit for a while and let folks chime in.

**Comment by angus19** [comment]
Kernel since 4.20 has the following in its Makefile. We need to merge [c4872e3](https://github.com/ayourtch/nat46/pull/21/commits/c4872e36530e14ac0b14ac69ba864ae67e5f15ea) therefore.

KBUILD_CFLAGS += $(call cc-option,-Wvla)
or
KBUILD_CFLAGS += -Wvla

**Comment by ayourtch** [comment]
Ok I think merging this one is a better idea than disabling the warning. If you confirm you are happy with the code in c4872e3, feel free to thumb up and i will merge it. I did not want to merge it "out of the blue" to avoid any surprises (after all it is a change in a promise, configuration-size wise), but it has been out there for more than a year so should not come as a surprise.

**Comment by angus19** [comment]
Please merge. Thanks.

**Pull request merged**
